language: node_js

node_js:
  - stable
  
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install boolbase nth-check
script:
  - istanbul cover -x **/lib/css-select/** -x **/dev/** node_modules/tape/bin/tape ./test/*.js
  - codecov