# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/me/wasp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/me/wasp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/wasp/CMakeFiles /Users/me/wasp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/wasp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wasp

# Build rule for target.
wasp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasp
.PHONY : wasp

# fast build rule for target.
wasp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/build
.PHONY : wasp/fast

source/Angle.o: source/Angle.cpp.o
.PHONY : source/Angle.o

# target to build an object file
source/Angle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.o
.PHONY : source/Angle.cpp.o

source/Angle.i: source/Angle.cpp.i
.PHONY : source/Angle.i

# target to preprocess a source file
source/Angle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.i
.PHONY : source/Angle.cpp.i

source/Angle.s: source/Angle.cpp.s
.PHONY : source/Angle.s

# target to generate assembly for a file
source/Angle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.s
.PHONY : source/Angle.cpp.s

source/Code.o: source/Code.cpp.o
.PHONY : source/Code.o

# target to build an object file
source/Code.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.o
.PHONY : source/Code.cpp.o

source/Code.i: source/Code.cpp.i
.PHONY : source/Code.i

# target to preprocess a source file
source/Code.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.i
.PHONY : source/Code.cpp.i

source/Code.s: source/Code.cpp.s
.PHONY : source/Code.s

# target to generate assembly for a file
source/Code.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.s
.PHONY : source/Code.cpp.s

source/Interpret.o: source/Interpret.cpp.o
.PHONY : source/Interpret.o

# target to build an object file
source/Interpret.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.o
.PHONY : source/Interpret.cpp.o

source/Interpret.i: source/Interpret.cpp.i
.PHONY : source/Interpret.i

# target to preprocess a source file
source/Interpret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.i
.PHONY : source/Interpret.cpp.i

source/Interpret.s: source/Interpret.cpp.s
.PHONY : source/Interpret.s

# target to generate assembly for a file
source/Interpret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.s
.PHONY : source/Interpret.cpp.s

source/List.o: source/List.cpp.o
.PHONY : source/List.o

# target to build an object file
source/List.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.o
.PHONY : source/List.cpp.o

source/List.i: source/List.cpp.i
.PHONY : source/List.i

# target to preprocess a source file
source/List.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.i
.PHONY : source/List.cpp.i

source/List.s: source/List.cpp.s
.PHONY : source/List.s

# target to generate assembly for a file
source/List.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.s
.PHONY : source/List.cpp.s

source/Map.o: source/Map.cpp.o
.PHONY : source/Map.o

# target to build an object file
source/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.o
.PHONY : source/Map.cpp.o

source/Map.i: source/Map.cpp.i
.PHONY : source/Map.i

# target to preprocess a source file
source/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.i
.PHONY : source/Map.cpp.i

source/Map.s: source/Map.cpp.s
.PHONY : source/Map.s

# target to generate assembly for a file
source/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.s
.PHONY : source/Map.cpp.s

source/Node.o: source/Node.cpp.o
.PHONY : source/Node.o

# target to build an object file
source/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.o
.PHONY : source/Node.cpp.o

source/Node.i: source/Node.cpp.i
.PHONY : source/Node.i

# target to preprocess a source file
source/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.i
.PHONY : source/Node.cpp.i

source/Node.s: source/Node.cpp.s
.PHONY : source/Node.s

# target to generate assembly for a file
source/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.s
.PHONY : source/Node.cpp.s

source/NodeTypes.o: source/NodeTypes.cpp.o
.PHONY : source/NodeTypes.o

# target to build an object file
source/NodeTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/NodeTypes.cpp.o
.PHONY : source/NodeTypes.cpp.o

source/NodeTypes.i: source/NodeTypes.cpp.i
.PHONY : source/NodeTypes.i

# target to preprocess a source file
source/NodeTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/NodeTypes.cpp.i
.PHONY : source/NodeTypes.cpp.i

source/NodeTypes.s: source/NodeTypes.cpp.s
.PHONY : source/NodeTypes.s

# target to generate assembly for a file
source/NodeTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/NodeTypes.cpp.s
.PHONY : source/NodeTypes.cpp.s

source/String.o: source/String.cpp.o
.PHONY : source/String.o

# target to build an object file
source/String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.o
.PHONY : source/String.cpp.o

source/String.i: source/String.cpp.i
.PHONY : source/String.i

# target to preprocess a source file
source/String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.i
.PHONY : source/String.cpp.i

source/String.s: source/String.cpp.s
.PHONY : source/String.s

# target to generate assembly for a file
source/String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.s
.PHONY : source/String.cpp.s

source/Util.o: source/Util.cpp.o
.PHONY : source/Util.o

# target to build an object file
source/Util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.o
.PHONY : source/Util.cpp.o

source/Util.i: source/Util.cpp.i
.PHONY : source/Util.i

# target to preprocess a source file
source/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.i
.PHONY : source/Util.cpp.i

source/Util.s: source/Util.cpp.s
.PHONY : source/Util.s

# target to generate assembly for a file
source/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.s
.PHONY : source/Util.cpp.s

source/Wasp.o: source/Wasp.cpp.o
.PHONY : source/Wasp.o

# target to build an object file
source/Wasp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.o
.PHONY : source/Wasp.cpp.o

source/Wasp.i: source/Wasp.cpp.i
.PHONY : source/Wasp.i

# target to preprocess a source file
source/Wasp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.i
.PHONY : source/Wasp.cpp.i

source/Wasp.s: source/Wasp.cpp.s
.PHONY : source/Wasp.s

# target to generate assembly for a file
source/Wasp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.s
.PHONY : source/Wasp.cpp.s

source/console.o: source/console.cpp.o
.PHONY : source/console.o

# target to build an object file
source/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.o
.PHONY : source/console.cpp.o

source/console.i: source/console.cpp.i
.PHONY : source/console.i

# target to preprocess a source file
source/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.i
.PHONY : source/console.cpp.i

source/console.s: source/console.cpp.s
.PHONY : source/console.s

# target to generate assembly for a file
source/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.s
.PHONY : source/console.cpp.s

source/own_merge/binary-reader-linker.o: source/own_merge/binary-reader-linker.cc.o
.PHONY : source/own_merge/binary-reader-linker.o

# target to build an object file
source/own_merge/binary-reader-linker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader-linker.cc.o
.PHONY : source/own_merge/binary-reader-linker.cc.o

source/own_merge/binary-reader-linker.i: source/own_merge/binary-reader-linker.cc.i
.PHONY : source/own_merge/binary-reader-linker.i

# target to preprocess a source file
source/own_merge/binary-reader-linker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader-linker.cc.i
.PHONY : source/own_merge/binary-reader-linker.cc.i

source/own_merge/binary-reader-linker.s: source/own_merge/binary-reader-linker.cc.s
.PHONY : source/own_merge/binary-reader-linker.s

# target to generate assembly for a file
source/own_merge/binary-reader-linker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader-linker.cc.s
.PHONY : source/own_merge/binary-reader-linker.cc.s

source/own_merge/binary-reader.o: source/own_merge/binary-reader.cc.o
.PHONY : source/own_merge/binary-reader.o

# target to build an object file
source/own_merge/binary-reader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader.cc.o
.PHONY : source/own_merge/binary-reader.cc.o

source/own_merge/binary-reader.i: source/own_merge/binary-reader.cc.i
.PHONY : source/own_merge/binary-reader.i

# target to preprocess a source file
source/own_merge/binary-reader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader.cc.i
.PHONY : source/own_merge/binary-reader.cc.i

source/own_merge/binary-reader.s: source/own_merge/binary-reader.cc.s
.PHONY : source/own_merge/binary-reader.s

# target to generate assembly for a file
source/own_merge/binary-reader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-reader.cc.s
.PHONY : source/own_merge/binary-reader.cc.s

source/own_merge/binary-writer.o: source/own_merge/binary-writer.cc.o
.PHONY : source/own_merge/binary-writer.o

# target to build an object file
source/own_merge/binary-writer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-writer.cc.o
.PHONY : source/own_merge/binary-writer.cc.o

source/own_merge/binary-writer.i: source/own_merge/binary-writer.cc.i
.PHONY : source/own_merge/binary-writer.i

# target to preprocess a source file
source/own_merge/binary-writer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-writer.cc.i
.PHONY : source/own_merge/binary-writer.cc.i

source/own_merge/binary-writer.s: source/own_merge/binary-writer.cc.s
.PHONY : source/own_merge/binary-writer.s

# target to generate assembly for a file
source/own_merge/binary-writer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary-writer.cc.s
.PHONY : source/own_merge/binary-writer.cc.s

source/own_merge/binary.o: source/own_merge/binary.cc.o
.PHONY : source/own_merge/binary.o

# target to build an object file
source/own_merge/binary.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary.cc.o
.PHONY : source/own_merge/binary.cc.o

source/own_merge/binary.i: source/own_merge/binary.cc.i
.PHONY : source/own_merge/binary.i

# target to preprocess a source file
source/own_merge/binary.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary.cc.i
.PHONY : source/own_merge/binary.cc.i

source/own_merge/binary.s: source/own_merge/binary.cc.s
.PHONY : source/own_merge/binary.s

# target to generate assembly for a file
source/own_merge/binary.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binary.cc.s
.PHONY : source/own_merge/binary.cc.s

source/own_merge/binding-hash.o: source/own_merge/binding-hash.cc.o
.PHONY : source/own_merge/binding-hash.o

# target to build an object file
source/own_merge/binding-hash.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binding-hash.cc.o
.PHONY : source/own_merge/binding-hash.cc.o

source/own_merge/binding-hash.i: source/own_merge/binding-hash.cc.i
.PHONY : source/own_merge/binding-hash.i

# target to preprocess a source file
source/own_merge/binding-hash.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binding-hash.cc.i
.PHONY : source/own_merge/binding-hash.cc.i

source/own_merge/binding-hash.s: source/own_merge/binding-hash.cc.s
.PHONY : source/own_merge/binding-hash.s

# target to generate assembly for a file
source/own_merge/binding-hash.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/binding-hash.cc.s
.PHONY : source/own_merge/binding-hash.cc.s

source/own_merge/common.o: source/own_merge/common.cc.o
.PHONY : source/own_merge/common.o

# target to build an object file
source/own_merge/common.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/common.cc.o
.PHONY : source/own_merge/common.cc.o

source/own_merge/common.i: source/own_merge/common.cc.i
.PHONY : source/own_merge/common.i

# target to preprocess a source file
source/own_merge/common.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/common.cc.i
.PHONY : source/own_merge/common.cc.i

source/own_merge/common.s: source/own_merge/common.cc.s
.PHONY : source/own_merge/common.s

# target to generate assembly for a file
source/own_merge/common.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/common.cc.s
.PHONY : source/own_merge/common.cc.s

source/own_merge/feature.o: source/own_merge/feature.cc.o
.PHONY : source/own_merge/feature.o

# target to build an object file
source/own_merge/feature.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/feature.cc.o
.PHONY : source/own_merge/feature.cc.o

source/own_merge/feature.i: source/own_merge/feature.cc.i
.PHONY : source/own_merge/feature.i

# target to preprocess a source file
source/own_merge/feature.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/feature.cc.i
.PHONY : source/own_merge/feature.cc.i

source/own_merge/feature.s: source/own_merge/feature.cc.s
.PHONY : source/own_merge/feature.s

# target to generate assembly for a file
source/own_merge/feature.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/feature.cc.s
.PHONY : source/own_merge/feature.cc.s

source/own_merge/ir.o: source/own_merge/ir.cc.o
.PHONY : source/own_merge/ir.o

# target to build an object file
source/own_merge/ir.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/ir.cc.o
.PHONY : source/own_merge/ir.cc.o

source/own_merge/ir.i: source/own_merge/ir.cc.i
.PHONY : source/own_merge/ir.i

# target to preprocess a source file
source/own_merge/ir.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/ir.cc.i
.PHONY : source/own_merge/ir.cc.i

source/own_merge/ir.s: source/own_merge/ir.cc.s
.PHONY : source/own_merge/ir.s

# target to generate assembly for a file
source/own_merge/ir.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/ir.cc.s
.PHONY : source/own_merge/ir.cc.s

source/own_merge/leb128.o: source/own_merge/leb128.cc.o
.PHONY : source/own_merge/leb128.o

# target to build an object file
source/own_merge/leb128.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/leb128.cc.o
.PHONY : source/own_merge/leb128.cc.o

source/own_merge/leb128.i: source/own_merge/leb128.cc.i
.PHONY : source/own_merge/leb128.i

# target to preprocess a source file
source/own_merge/leb128.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/leb128.cc.i
.PHONY : source/own_merge/leb128.cc.i

source/own_merge/leb128.s: source/own_merge/leb128.cc.s
.PHONY : source/own_merge/leb128.s

# target to generate assembly for a file
source/own_merge/leb128.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/leb128.cc.s
.PHONY : source/own_merge/leb128.cc.s

source/own_merge/opcode-code-table.o: source/own_merge/opcode-code-table.c.o
.PHONY : source/own_merge/opcode-code-table.o

# target to build an object file
source/own_merge/opcode-code-table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode-code-table.c.o
.PHONY : source/own_merge/opcode-code-table.c.o

source/own_merge/opcode-code-table.i: source/own_merge/opcode-code-table.c.i
.PHONY : source/own_merge/opcode-code-table.i

# target to preprocess a source file
source/own_merge/opcode-code-table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode-code-table.c.i
.PHONY : source/own_merge/opcode-code-table.c.i

source/own_merge/opcode-code-table.s: source/own_merge/opcode-code-table.c.s
.PHONY : source/own_merge/opcode-code-table.s

# target to generate assembly for a file
source/own_merge/opcode-code-table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode-code-table.c.s
.PHONY : source/own_merge/opcode-code-table.c.s

source/own_merge/opcode.o: source/own_merge/opcode.cc.o
.PHONY : source/own_merge/opcode.o

# target to build an object file
source/own_merge/opcode.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode.cc.o
.PHONY : source/own_merge/opcode.cc.o

source/own_merge/opcode.i: source/own_merge/opcode.cc.i
.PHONY : source/own_merge/opcode.i

# target to preprocess a source file
source/own_merge/opcode.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode.cc.i
.PHONY : source/own_merge/opcode.cc.i

source/own_merge/opcode.s: source/own_merge/opcode.cc.s
.PHONY : source/own_merge/opcode.s

# target to generate assembly for a file
source/own_merge/opcode.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/opcode.cc.s
.PHONY : source/own_merge/opcode.cc.s

source/own_merge/stream.o: source/own_merge/stream.cc.o
.PHONY : source/own_merge/stream.o

# target to build an object file
source/own_merge/stream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/stream.cc.o
.PHONY : source/own_merge/stream.cc.o

source/own_merge/stream.i: source/own_merge/stream.cc.i
.PHONY : source/own_merge/stream.i

# target to preprocess a source file
source/own_merge/stream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/stream.cc.i
.PHONY : source/own_merge/stream.cc.i

source/own_merge/stream.s: source/own_merge/stream.cc.s
.PHONY : source/own_merge/stream.s

# target to generate assembly for a file
source/own_merge/stream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/stream.cc.s
.PHONY : source/own_merge/stream.cc.s

source/own_merge/utf8.o: source/own_merge/utf8.cc.o
.PHONY : source/own_merge/utf8.o

# target to build an object file
source/own_merge/utf8.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/utf8.cc.o
.PHONY : source/own_merge/utf8.cc.o

source/own_merge/utf8.i: source/own_merge/utf8.cc.i
.PHONY : source/own_merge/utf8.i

# target to preprocess a source file
source/own_merge/utf8.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/utf8.cc.i
.PHONY : source/own_merge/utf8.cc.i

source/own_merge/utf8.s: source/own_merge/utf8.cc.s
.PHONY : source/own_merge/utf8.s

# target to generate assembly for a file
source/own_merge/utf8.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/own_merge/utf8.cc.s
.PHONY : source/own_merge/utf8.cc.s

source/smart_types.o: source/smart_types.cpp.o
.PHONY : source/smart_types.o

# target to build an object file
source/smart_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/smart_types.cpp.o
.PHONY : source/smart_types.cpp.o

source/smart_types.i: source/smart_types.cpp.i
.PHONY : source/smart_types.i

# target to preprocess a source file
source/smart_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/smart_types.cpp.i
.PHONY : source/smart_types.cpp.i

source/smart_types.s: source/smart_types.cpp.s
.PHONY : source/smart_types.s

# target to generate assembly for a file
source/smart_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/smart_types.cpp.s
.PHONY : source/smart_types.cpp.s

source/tests.o: source/tests.cpp.o
.PHONY : source/tests.o

# target to build an object file
source/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.o
.PHONY : source/tests.cpp.o

source/tests.i: source/tests.cpp.i
.PHONY : source/tests.i

# target to preprocess a source file
source/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.i
.PHONY : source/tests.cpp.i

source/tests.s: source/tests.cpp.s
.PHONY : source/tests.s

# target to generate assembly for a file
source/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.s
.PHONY : source/tests.cpp.s

source/wasm_emitter.o: source/wasm_emitter.cpp.o
.PHONY : source/wasm_emitter.o

# target to build an object file
source/wasm_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.o
.PHONY : source/wasm_emitter.cpp.o

source/wasm_emitter.i: source/wasm_emitter.cpp.i
.PHONY : source/wasm_emitter.i

# target to preprocess a source file
source/wasm_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.i
.PHONY : source/wasm_emitter.cpp.i

source/wasm_emitter.s: source/wasm_emitter.cpp.s
.PHONY : source/wasm_emitter.s

# target to generate assembly for a file
source/wasm_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.s
.PHONY : source/wasm_emitter.cpp.s

source/wasm_helpers.o: source/wasm_helpers.cpp.o
.PHONY : source/wasm_helpers.o

# target to build an object file
source/wasm_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.o
.PHONY : source/wasm_helpers.cpp.o

source/wasm_helpers.i: source/wasm_helpers.cpp.i
.PHONY : source/wasm_helpers.i

# target to preprocess a source file
source/wasm_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.i
.PHONY : source/wasm_helpers.cpp.i

source/wasm_helpers.s: source/wasm_helpers.cpp.s
.PHONY : source/wasm_helpers.s

# target to generate assembly for a file
source/wasm_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.s
.PHONY : source/wasm_helpers.cpp.s

source/wasm_helpers_host.o: source/wasm_helpers_host.cpp.o
.PHONY : source/wasm_helpers_host.o

# target to build an object file
source/wasm_helpers_host.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers_host.cpp.o
.PHONY : source/wasm_helpers_host.cpp.o

source/wasm_helpers_host.i: source/wasm_helpers_host.cpp.i
.PHONY : source/wasm_helpers_host.i

# target to preprocess a source file
source/wasm_helpers_host.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers_host.cpp.i
.PHONY : source/wasm_helpers_host.cpp.i

source/wasm_helpers_host.s: source/wasm_helpers_host.cpp.s
.PHONY : source/wasm_helpers_host.s

# target to generate assembly for a file
source/wasm_helpers_host.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers_host.cpp.s
.PHONY : source/wasm_helpers_host.cpp.s

source/wasm_linker.o: source/wasm_linker.cpp.o
.PHONY : source/wasm_linker.o

# target to build an object file
source/wasm_linker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_linker.cpp.o
.PHONY : source/wasm_linker.cpp.o

source/wasm_linker.i: source/wasm_linker.cpp.i
.PHONY : source/wasm_linker.i

# target to preprocess a source file
source/wasm_linker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_linker.cpp.i
.PHONY : source/wasm_linker.cpp.i

source/wasm_linker.s: source/wasm_linker.cpp.s
.PHONY : source/wasm_linker.s

# target to generate assembly for a file
source/wasm_linker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_linker.cpp.s
.PHONY : source/wasm_linker.cpp.s

source/wasm_reader.o: source/wasm_reader.cpp.o
.PHONY : source/wasm_reader.o

# target to build an object file
source/wasm_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.o
.PHONY : source/wasm_reader.cpp.o

source/wasm_reader.i: source/wasm_reader.cpp.i
.PHONY : source/wasm_reader.i

# target to preprocess a source file
source/wasm_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.i
.PHONY : source/wasm_reader.cpp.i

source/wasm_reader.s: source/wasm_reader.cpp.s
.PHONY : source/wasm_reader.s

# target to generate assembly for a file
source/wasm_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.s
.PHONY : source/wasm_reader.cpp.s

source/wasm_runner_edge.o: source/wasm_runner_edge.cpp.o
.PHONY : source/wasm_runner_edge.o

# target to build an object file
source/wasm_runner_edge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_runner_edge.cpp.o
.PHONY : source/wasm_runner_edge.cpp.o

source/wasm_runner_edge.i: source/wasm_runner_edge.cpp.i
.PHONY : source/wasm_runner_edge.i

# target to preprocess a source file
source/wasm_runner_edge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_runner_edge.cpp.i
.PHONY : source/wasm_runner_edge.cpp.i

source/wasm_runner_edge.s: source/wasm_runner_edge.cpp.s
.PHONY : source/wasm_runner_edge.s

# target to generate assembly for a file
source/wasm_runner_edge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_runner_edge.cpp.s
.PHONY : source/wasm_runner_edge.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wasp"
	@echo "... source/Angle.o"
	@echo "... source/Angle.i"
	@echo "... source/Angle.s"
	@echo "... source/Code.o"
	@echo "... source/Code.i"
	@echo "... source/Code.s"
	@echo "... source/Interpret.o"
	@echo "... source/Interpret.i"
	@echo "... source/Interpret.s"
	@echo "... source/List.o"
	@echo "... source/List.i"
	@echo "... source/List.s"
	@echo "... source/Map.o"
	@echo "... source/Map.i"
	@echo "... source/Map.s"
	@echo "... source/Node.o"
	@echo "... source/Node.i"
	@echo "... source/Node.s"
	@echo "... source/NodeTypes.o"
	@echo "... source/NodeTypes.i"
	@echo "... source/NodeTypes.s"
	@echo "... source/String.o"
	@echo "... source/String.i"
	@echo "... source/String.s"
	@echo "... source/Util.o"
	@echo "... source/Util.i"
	@echo "... source/Util.s"
	@echo "... source/Wasp.o"
	@echo "... source/Wasp.i"
	@echo "... source/Wasp.s"
	@echo "... source/console.o"
	@echo "... source/console.i"
	@echo "... source/console.s"
	@echo "... source/own_merge/binary-reader-linker.o"
	@echo "... source/own_merge/binary-reader-linker.i"
	@echo "... source/own_merge/binary-reader-linker.s"
	@echo "... source/own_merge/binary-reader.o"
	@echo "... source/own_merge/binary-reader.i"
	@echo "... source/own_merge/binary-reader.s"
	@echo "... source/own_merge/binary-writer.o"
	@echo "... source/own_merge/binary-writer.i"
	@echo "... source/own_merge/binary-writer.s"
	@echo "... source/own_merge/binary.o"
	@echo "... source/own_merge/binary.i"
	@echo "... source/own_merge/binary.s"
	@echo "... source/own_merge/binding-hash.o"
	@echo "... source/own_merge/binding-hash.i"
	@echo "... source/own_merge/binding-hash.s"
	@echo "... source/own_merge/common.o"
	@echo "... source/own_merge/common.i"
	@echo "... source/own_merge/common.s"
	@echo "... source/own_merge/feature.o"
	@echo "... source/own_merge/feature.i"
	@echo "... source/own_merge/feature.s"
	@echo "... source/own_merge/ir.o"
	@echo "... source/own_merge/ir.i"
	@echo "... source/own_merge/ir.s"
	@echo "... source/own_merge/leb128.o"
	@echo "... source/own_merge/leb128.i"
	@echo "... source/own_merge/leb128.s"
	@echo "... source/own_merge/opcode-code-table.o"
	@echo "... source/own_merge/opcode-code-table.i"
	@echo "... source/own_merge/opcode-code-table.s"
	@echo "... source/own_merge/opcode.o"
	@echo "... source/own_merge/opcode.i"
	@echo "... source/own_merge/opcode.s"
	@echo "... source/own_merge/stream.o"
	@echo "... source/own_merge/stream.i"
	@echo "... source/own_merge/stream.s"
	@echo "... source/own_merge/utf8.o"
	@echo "... source/own_merge/utf8.i"
	@echo "... source/own_merge/utf8.s"
	@echo "... source/smart_types.o"
	@echo "... source/smart_types.i"
	@echo "... source/smart_types.s"
	@echo "... source/tests.o"
	@echo "... source/tests.i"
	@echo "... source/tests.s"
	@echo "... source/wasm_emitter.o"
	@echo "... source/wasm_emitter.i"
	@echo "... source/wasm_emitter.s"
	@echo "... source/wasm_helpers.o"
	@echo "... source/wasm_helpers.i"
	@echo "... source/wasm_helpers.s"
	@echo "... source/wasm_helpers_host.o"
	@echo "... source/wasm_helpers_host.i"
	@echo "... source/wasm_helpers_host.s"
	@echo "... source/wasm_linker.o"
	@echo "... source/wasm_linker.i"
	@echo "... source/wasm_linker.s"
	@echo "... source/wasm_reader.o"
	@echo "... source/wasm_reader.i"
	@echo "... source/wasm_reader.s"
	@echo "... source/wasm_runner_edge.o"
	@echo "... source/wasm_runner_edge.i"
	@echo "... source/wasm_runner_edge.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

