# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/me/dev/apps/wasp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/me/dev/apps/wasp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/dev/apps/wasp/CMakeFiles /Users/me/dev/apps/wasp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/dev/apps/wasp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wasp

# Build rule for target.
wasp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasp
.PHONY : wasp

# fast build rule for target.
wasp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/build
.PHONY : wasp/fast

source/Angle.o: source/Angle.cpp.o
.PHONY : source/Angle.o

# target to build an object file
source/Angle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.o
.PHONY : source/Angle.cpp.o

source/Angle.i: source/Angle.cpp.i
.PHONY : source/Angle.i

# target to preprocess a source file
source/Angle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.i
.PHONY : source/Angle.cpp.i

source/Angle.s: source/Angle.cpp.s
.PHONY : source/Angle.s

# target to generate assembly for a file
source/Angle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Angle.cpp.s
.PHONY : source/Angle.cpp.s

source/Backtrace.o: source/Backtrace.cpp.o
.PHONY : source/Backtrace.o

# target to build an object file
source/Backtrace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Backtrace.cpp.o
.PHONY : source/Backtrace.cpp.o

source/Backtrace.i: source/Backtrace.cpp.i
.PHONY : source/Backtrace.i

# target to preprocess a source file
source/Backtrace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Backtrace.cpp.i
.PHONY : source/Backtrace.cpp.i

source/Backtrace.s: source/Backtrace.cpp.s
.PHONY : source/Backtrace.s

# target to generate assembly for a file
source/Backtrace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Backtrace.cpp.s
.PHONY : source/Backtrace.cpp.s

source/Code.o: source/Code.cpp.o
.PHONY : source/Code.o

# target to build an object file
source/Code.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.o
.PHONY : source/Code.cpp.o

source/Code.i: source/Code.cpp.i
.PHONY : source/Code.i

# target to preprocess a source file
source/Code.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.i
.PHONY : source/Code.cpp.i

source/Code.s: source/Code.cpp.s
.PHONY : source/Code.s

# target to generate assembly for a file
source/Code.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Code.cpp.s
.PHONY : source/Code.cpp.s

source/Interpret.o: source/Interpret.cpp.o
.PHONY : source/Interpret.o

# target to build an object file
source/Interpret.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.o
.PHONY : source/Interpret.cpp.o

source/Interpret.i: source/Interpret.cpp.i
.PHONY : source/Interpret.i

# target to preprocess a source file
source/Interpret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.i
.PHONY : source/Interpret.cpp.i

source/Interpret.s: source/Interpret.cpp.s
.PHONY : source/Interpret.s

# target to generate assembly for a file
source/Interpret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Interpret.cpp.s
.PHONY : source/Interpret.cpp.s

source/List.o: source/List.cpp.o
.PHONY : source/List.o

# target to build an object file
source/List.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.o
.PHONY : source/List.cpp.o

source/List.i: source/List.cpp.i
.PHONY : source/List.i

# target to preprocess a source file
source/List.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.i
.PHONY : source/List.cpp.i

source/List.s: source/List.cpp.s
.PHONY : source/List.s

# target to generate assembly for a file
source/List.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/List.cpp.s
.PHONY : source/List.cpp.s

source/Map.o: source/Map.cpp.o
.PHONY : source/Map.o

# target to build an object file
source/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.o
.PHONY : source/Map.cpp.o

source/Map.i: source/Map.cpp.i
.PHONY : source/Map.i

# target to preprocess a source file
source/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.i
.PHONY : source/Map.cpp.i

source/Map.s: source/Map.cpp.s
.PHONY : source/Map.s

# target to generate assembly for a file
source/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Map.cpp.s
.PHONY : source/Map.cpp.s

source/Node.o: source/Node.cpp.o
.PHONY : source/Node.o

# target to build an object file
source/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.o
.PHONY : source/Node.cpp.o

source/Node.i: source/Node.cpp.i
.PHONY : source/Node.i

# target to preprocess a source file
source/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.i
.PHONY : source/Node.cpp.i

source/Node.s: source/Node.cpp.s
.PHONY : source/Node.s

# target to generate assembly for a file
source/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Node.cpp.s
.PHONY : source/Node.cpp.s

source/String.o: source/String.cpp.o
.PHONY : source/String.o

# target to build an object file
source/String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.o
.PHONY : source/String.cpp.o

source/String.i: source/String.cpp.i
.PHONY : source/String.i

# target to preprocess a source file
source/String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.i
.PHONY : source/String.cpp.i

source/String.s: source/String.cpp.s
.PHONY : source/String.s

# target to generate assembly for a file
source/String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/String.cpp.s
.PHONY : source/String.cpp.s

source/Util.o: source/Util.cpp.o
.PHONY : source/Util.o

# target to build an object file
source/Util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.o
.PHONY : source/Util.cpp.o

source/Util.i: source/Util.cpp.i
.PHONY : source/Util.i

# target to preprocess a source file
source/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.i
.PHONY : source/Util.cpp.i

source/Util.s: source/Util.cpp.s
.PHONY : source/Util.s

# target to generate assembly for a file
source/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Util.cpp.s
.PHONY : source/Util.cpp.s

source/Wasp.o: source/Wasp.cpp.o
.PHONY : source/Wasp.o

# target to build an object file
source/Wasp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.o
.PHONY : source/Wasp.cpp.o

source/Wasp.i: source/Wasp.cpp.i
.PHONY : source/Wasp.i

# target to preprocess a source file
source/Wasp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.i
.PHONY : source/Wasp.cpp.i

source/Wasp.s: source/Wasp.cpp.s
.PHONY : source/Wasp.s

# target to generate assembly for a file
source/Wasp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/Wasp.cpp.s
.PHONY : source/Wasp.cpp.s

source/console.o: source/console.cpp.o
.PHONY : source/console.o

# target to build an object file
source/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.o
.PHONY : source/console.cpp.o

source/console.i: source/console.cpp.i
.PHONY : source/console.i

# target to preprocess a source file
source/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.i
.PHONY : source/console.cpp.i

source/console.s: source/console.cpp.s
.PHONY : source/console.s

# target to generate assembly for a file
source/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/console.cpp.s
.PHONY : source/console.cpp.s

source/tests.o: source/tests.cpp.o
.PHONY : source/tests.o

# target to build an object file
source/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.o
.PHONY : source/tests.cpp.o

source/tests.i: source/tests.cpp.i
.PHONY : source/tests.i

# target to preprocess a source file
source/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.i
.PHONY : source/tests.cpp.i

source/tests.s: source/tests.cpp.s
.PHONY : source/tests.s

# target to generate assembly for a file
source/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/tests.cpp.s
.PHONY : source/tests.cpp.s

source/wasm_emitter.o: source/wasm_emitter.cpp.o
.PHONY : source/wasm_emitter.o

# target to build an object file
source/wasm_emitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.o
.PHONY : source/wasm_emitter.cpp.o

source/wasm_emitter.i: source/wasm_emitter.cpp.i
.PHONY : source/wasm_emitter.i

# target to preprocess a source file
source/wasm_emitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.i
.PHONY : source/wasm_emitter.cpp.i

source/wasm_emitter.s: source/wasm_emitter.cpp.s
.PHONY : source/wasm_emitter.s

# target to generate assembly for a file
source/wasm_emitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_emitter.cpp.s
.PHONY : source/wasm_emitter.cpp.s

source/wasm_helpers.o: source/wasm_helpers.cpp.o
.PHONY : source/wasm_helpers.o

# target to build an object file
source/wasm_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.o
.PHONY : source/wasm_helpers.cpp.o

source/wasm_helpers.i: source/wasm_helpers.cpp.i
.PHONY : source/wasm_helpers.i

# target to preprocess a source file
source/wasm_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.i
.PHONY : source/wasm_helpers.cpp.i

source/wasm_helpers.s: source/wasm_helpers.cpp.s
.PHONY : source/wasm_helpers.s

# target to generate assembly for a file
source/wasm_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_helpers.cpp.s
.PHONY : source/wasm_helpers.cpp.s

source/wasm_merger.o: source/wasm_merger.cpp.o
.PHONY : source/wasm_merger.o

# target to build an object file
source/wasm_merger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_merger.cpp.o
.PHONY : source/wasm_merger.cpp.o

source/wasm_merger.i: source/wasm_merger.cpp.i
.PHONY : source/wasm_merger.i

# target to preprocess a source file
source/wasm_merger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_merger.cpp.i
.PHONY : source/wasm_merger.cpp.i

source/wasm_merger.s: source/wasm_merger.cpp.s
.PHONY : source/wasm_merger.s

# target to generate assembly for a file
source/wasm_merger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_merger.cpp.s
.PHONY : source/wasm_merger.cpp.s

source/wasm_reader.o: source/wasm_reader.cpp.o
.PHONY : source/wasm_reader.o

# target to build an object file
source/wasm_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.o
.PHONY : source/wasm_reader.cpp.o

source/wasm_reader.i: source/wasm_reader.cpp.i
.PHONY : source/wasm_reader.i

# target to preprocess a source file
source/wasm_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.i
.PHONY : source/wasm_reader.cpp.i

source/wasm_reader.s: source/wasm_reader.cpp.s
.PHONY : source/wasm_reader.s

# target to generate assembly for a file
source/wasm_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasm_reader.cpp.s
.PHONY : source/wasm_reader.cpp.s

source/wasmtime_runner.o: source/wasmtime_runner.cpp.o
.PHONY : source/wasmtime_runner.o

# target to build an object file
source/wasmtime_runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasmtime_runner.cpp.o
.PHONY : source/wasmtime_runner.cpp.o

source/wasmtime_runner.i: source/wasmtime_runner.cpp.i
.PHONY : source/wasmtime_runner.i

# target to preprocess a source file
source/wasmtime_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasmtime_runner.cpp.i
.PHONY : source/wasmtime_runner.cpp.i

source/wasmtime_runner.s: source/wasmtime_runner.cpp.s
.PHONY : source/wasmtime_runner.s

# target to generate assembly for a file
source/wasmtime_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasp.dir/build.make CMakeFiles/wasp.dir/source/wasmtime_runner.cpp.s
.PHONY : source/wasmtime_runner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wasp"
	@echo "... source/Angle.o"
	@echo "... source/Angle.i"
	@echo "... source/Angle.s"
	@echo "... source/Backtrace.o"
	@echo "... source/Backtrace.i"
	@echo "... source/Backtrace.s"
	@echo "... source/Code.o"
	@echo "... source/Code.i"
	@echo "... source/Code.s"
	@echo "... source/Interpret.o"
	@echo "... source/Interpret.i"
	@echo "... source/Interpret.s"
	@echo "... source/List.o"
	@echo "... source/List.i"
	@echo "... source/List.s"
	@echo "... source/Map.o"
	@echo "... source/Map.i"
	@echo "... source/Map.s"
	@echo "... source/Node.o"
	@echo "... source/Node.i"
	@echo "... source/Node.s"
	@echo "... source/String.o"
	@echo "... source/String.i"
	@echo "... source/String.s"
	@echo "... source/Util.o"
	@echo "... source/Util.i"
	@echo "... source/Util.s"
	@echo "... source/Wasp.o"
	@echo "... source/Wasp.i"
	@echo "... source/Wasp.s"
	@echo "... source/console.o"
	@echo "... source/console.i"
	@echo "... source/console.s"
	@echo "... source/tests.o"
	@echo "... source/tests.i"
	@echo "... source/tests.s"
	@echo "... source/wasm_emitter.o"
	@echo "... source/wasm_emitter.i"
	@echo "... source/wasm_emitter.s"
	@echo "... source/wasm_helpers.o"
	@echo "... source/wasm_helpers.i"
	@echo "... source/wasm_helpers.s"
	@echo "... source/wasm_merger.o"
	@echo "... source/wasm_merger.i"
	@echo "... source/wasm_merger.s"
	@echo "... source/wasm_reader.o"
	@echo "... source/wasm_reader.i"
	@echo "... source/wasm_reader.s"
	@echo "... source/wasmtime_runner.o"
	@echo "... source/wasmtime_runner.i"
	@echo "... source/wasmtime_runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

