# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/me/wasp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/me/wasp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/wasp/CMakeFiles /Users/me/wasp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/me/wasp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BuildWasp

# Build rule for target.
BuildWasp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BuildWasp
.PHONY : BuildWasp

# fast build rule for target.
BuildWasp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BuildWasp.dir/build.make CMakeFiles/BuildWasp.dir/build
.PHONY : BuildWasp/fast

#=============================================================================
# Target rules for targets named angle

# Build rule for target.
angle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 angle
.PHONY : angle

# fast build rule for target.
angle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/build
.PHONY : angle/fast

Angle.o: Angle.cpp.o

.PHONY : Angle.o

# target to build an object file
Angle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Angle.cpp.o
.PHONY : Angle.cpp.o

Angle.i: Angle.cpp.i

.PHONY : Angle.i

# target to preprocess a source file
Angle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Angle.cpp.i
.PHONY : Angle.cpp.i

Angle.s: Angle.cpp.s

.PHONY : Angle.s

# target to generate assembly for a file
Angle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Angle.cpp.s
.PHONY : Angle.cpp.s

Map.o: Map.cpp.o

.PHONY : Map.o

# target to build an object file
Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Map.cpp.o
.PHONY : Map.cpp.o

Map.i: Map.cpp.i

.PHONY : Map.i

# target to preprocess a source file
Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Map.cpp.i
.PHONY : Map.cpp.i

Map.s: Map.cpp.s

.PHONY : Map.s

# target to generate assembly for a file
Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Map.cpp.s
.PHONY : Map.cpp.s

Node.o: Node.cpp.o

.PHONY : Node.o

# target to build an object file
Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Node.cpp.o
.PHONY : Node.cpp.o

Node.i: Node.cpp.i

.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s

.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Node.cpp.s
.PHONY : Node.cpp.s

String.o: String.cpp.o

.PHONY : String.o

# target to build an object file
String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/String.cpp.o
.PHONY : String.cpp.o

String.i: String.cpp.i

.PHONY : String.i

# target to preprocess a source file
String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/String.cpp.i
.PHONY : String.cpp.i

String.s: String.cpp.s

.PHONY : String.s

# target to generate assembly for a file
String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/String.cpp.s
.PHONY : String.cpp.s

Wasp.o: Wasp.cpp.o

.PHONY : Wasp.o

# target to build an object file
Wasp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Wasp.cpp.o
.PHONY : Wasp.cpp.o

Wasp.i: Wasp.cpp.i

.PHONY : Wasp.i

# target to preprocess a source file
Wasp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Wasp.cpp.i
.PHONY : Wasp.cpp.i

Wasp.s: Wasp.cpp.s

.PHONY : Wasp.s

# target to generate assembly for a file
Wasp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/Wasp.cpp.s
.PHONY : Wasp.cpp.s

wasm_helpers.o: wasm_helpers.cpp.o

.PHONY : wasm_helpers.o

# target to build an object file
wasm_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/wasm_helpers.cpp.o
.PHONY : wasm_helpers.cpp.o

wasm_helpers.i: wasm_helpers.cpp.i

.PHONY : wasm_helpers.i

# target to preprocess a source file
wasm_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/wasm_helpers.cpp.i
.PHONY : wasm_helpers.cpp.i

wasm_helpers.s: wasm_helpers.cpp.s

.PHONY : wasm_helpers.s

# target to generate assembly for a file
wasm_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angle.dir/build.make CMakeFiles/angle.dir/wasm_helpers.cpp.s
.PHONY : wasm_helpers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BuildWasp"
	@echo "... angle"
	@echo "... Angle.o"
	@echo "... Angle.i"
	@echo "... Angle.s"
	@echo "... Map.o"
	@echo "... Map.i"
	@echo "... Map.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... String.o"
	@echo "... String.i"
	@echo "... String.s"
	@echo "... Wasp.o"
	@echo "... Wasp.i"
	@echo "... Wasp.s"
	@echo "... wasm_helpers.o"
	@echo "... wasm_helpers.i"
	@echo "... wasm_helpers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

