spin_version = "1"
authors = ["Pannous <info@pannous.net>"]
description = "example http-rust library"
name = "hello"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/hello.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
