/* Automatically generated by wasm2c */
#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO: only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double float64;
#endif

#include "wasm.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct Z__instance_t {
    wasm_rt_memory_t w2c_M0;
    wasm_rt_funcref_table_t w2c_T0;
} Z__instance_t;

void Z__init_module(void);

void Z__instantiate(Z__instance_t *);

void Z__free(Z__instance_t *);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_H_GENERATED_ */
/* Automatically generated by wasm2c */
#include <assert.h>
#include <math.h>
#include <stddef.h>
#include <string.h>

#if defined(_MSC_VER)
#include <intrin.h>
#include <malloc.h>
#define alloca _alloca
#else

#include <alloca.h>

#endif


#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_USE_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#define UNREACHABLE TRAP(UNREACHABLE)

#define CALL_INDIRECT(table, t, ft, x, ...)             \
  (LIKELY((x) < table.size && table.data[x].func &&     \
          table.data[x].func_type == func_types[ft]) || \
       TRAP(CALL_INDIRECT),                             \
   ((t)table.data[x].func)(__VA_ARGS__))

#define RANGE_CHECK(mem, offset, len)               \
  if (UNLIKELY(offset + (uint64_t)len > mem->size)) \
    TRAP(OOB);

#if WASM_RT_MEMCHECK_SIGNAL_HANDLER
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t) RANGE_CHECK(mem, a, sizeof(t))
#endif

#ifdef __GNUC__
#define wasm_asm __asm__
#else
#define wasm_asm(X)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void* dest, const void* src, size_t n) {
  size_t i = 0;
  u8* dest_chars = dest;
  memcpy(dest, src, n);
  for (i = 0; i < (n >> 1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s)                   \
  do {                                          \
    RANGE_CHECK((&m), m.size - o - s, s);       \
    load_data(&(m.data[m.size - o - s]), i, s); \
  } while (0)
#define DEFINE_LOAD(name, t1, t2, t3)                                  \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {             \
    MEMCHECK(mem, addr, t1);                                           \
    t1 result;                                                         \
    wasm_rt_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], \
                   sizeof(t1));                                        \
    wasm_asm("" ::"r"(result));                                        \
    return (t3)(t2)result;                                             \
  }

#define DEFINE_STORE(name, t1, t2)                                      \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {  \
    MEMCHECK(mem, addr, t1);                                            \
    t1 wrapped = (t1)value;                                             \
    wasm_rt_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, \
                   sizeof(t1));                                         \
  }
#else

static inline void load_data(void *dest, const void *src, size_t n) {
    memcpy(dest, src, n);
}

#define LOAD_DATA(m, o, i, s)      \
  do {                             \
    RANGE_CHECK((&m), o, s);       \
    load_data(&(m.data[o]), i, s); \
  } while (0)
#define DEFINE_LOAD(name, t1, t2, t3)                      \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) { \
    MEMCHECK(mem, addr, t1);                               \
    t1 result;                                             \
    wasm_rt_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    wasm_asm("" ::"r"(result));                            \
    return (t3)(t2)result;                                 \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    wasm_rt_memcpy(&mem->data[addr], &wrapped, sizeof(t1));            \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32)

DEFINE_LOAD(i64_load, u64, u64, u64)

DEFINE_LOAD(f32_load, f32, f32, f32)

DEFINE_LOAD(f64_load, float64, float64, float64)

DEFINE_LOAD(i32_load8_s, s8, s32, u32)

DEFINE_LOAD(i64_load8_s, s8, s64, u64)

DEFINE_LOAD(i32_load8_u, u8, u32, u32)

DEFINE_LOAD(i64_load8_u, u8, u64, u64)

DEFINE_LOAD(i32_load16_s, s16, s32, u32)

DEFINE_LOAD(i64_load16_s, s16, s64, u64)

DEFINE_LOAD(i32_load16_u, u16, u32, u32)

DEFINE_LOAD(i64_load16_u, u16, u64, u64)

DEFINE_LOAD(i64_load32_s, s32, s64, u64)

DEFINE_LOAD(i64_load32_u, u32, u64, u64)

DEFINE_STORE(i32_store, u32, u32)

DEFINE_STORE(i64_store, u64, u64)

DEFINE_STORE(f32_store, f32, f32)

DEFINE_STORE(f64_store, float64, float64)

DEFINE_STORE(i32_store8, u8, u32)

DEFINE_STORE(i32_store16, u16, u32)

DEFINE_STORE(i64_store8, u8, u64)

DEFINE_STORE(i64_store16, u16, u64)

DEFINE_STORE(i64_store32, u32, u64)

#if defined(_MSC_VER)

// Adapted from
// https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h

static inline int I64_CLZ(unsigned long long v) {
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  if (_BitScanReverse64(&r, v)) {
    return 63 - r;
  }
#else
  if (_BitScanReverse(&r, (unsigned long)(v >> 32))) {
    return 31 - r;
  } else if (_BitScanReverse(&r, (unsigned long)v)) {
    return 63 - r;
  }
#endif
  return 64;
}

static inline int I32_CLZ(unsigned long v) {
  unsigned long r = 0;
  if (_BitScanReverse(&r, v)) {
    return 31 - r;
  }
  return 32;
}

static inline int I64_CTZ(unsigned long long v) {
  if (!v) {
    return 64;
  }
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  _BitScanForward64(&r, v);
  return (int)r;
#else
  if (_BitScanForward(&r, (unsigned int)(v))) {
    return (int)(r);
  }

  _BitScanForward(&r, (unsigned int)(v >> 32));
  return (int)(r + 32);
#endif
}

static inline int I32_CTZ(unsigned long v) {
  if (!v) {
    return 32;
  }
  unsigned long r = 0;
  _BitScanForward(&r, v);
  return (int)r;
}

#define POPCOUNT_DEFINE_PORTABLE(f_n, T)                            \
  static inline u32 f_n(T x) {                                      \
    x = x - ((x >> 1) & (T) ~(T)0 / 3);                             \
    x = (x & (T) ~(T)0 / 15 * 3) + ((x >> 2) & (T) ~(T)0 / 15 * 3); \
    x = (x + (x >> 4)) & (T) ~(T)0 / 255 * 15;                      \
    return (T)(x * ((T) ~(T)0 / 255)) >> (sizeof(T) - 1) * 8;       \
  }

POPCOUNT_DEFINE_PORTABLE(I32_POPCNT, u32)
POPCOUNT_DEFINE_PORTABLE(I64_POPCNT, u64)

#undef POPCOUNT_DEFINE_PORTABLE

#else

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#endif

#define DIV_S(ut, min, x, y)                                      \
  ((UNLIKELY((y) == 0))                                           \
       ? TRAP(DIV_BY_ZERO)                                        \
       : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                             : (ut)((x) / (y)))

#define REM_S(ut, min, x, y) \
  ((UNLIKELY((y) == 0))      \
       ? TRAP(DIV_BY_ZERO)   \
       : (UNLIKELY((x) == min && (y) == -1)) ? 0 : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
                                                : (x < y) ? x : y)

#define FMAX(x, y)                                                     \
  ((UNLIKELY((x) != (x)))                                              \
       ? NAN                                                           \
       : (UNLIKELY((y) != (y)))                                        \
             ? NAN                                                     \
             : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
                                                : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                           \
  ((UNLIKELY((x) != (x)))                                                 \
       ? TRAP(INVALID_CONVERSION)                                         \
       : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                     : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) \
  TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) \
  TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) \
  TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) \
  TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                          \
  ((UNLIKELY((x) != (x)))                                                \
       ? TRAP(INVALID_CONVERSION)                                        \
       : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW) \
                                                    : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296., x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))                                       \
       ? 0                                                      \
       : (UNLIKELY(!((x)minop(min))))                           \
             ? smin                                             \
             : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x)                                            \
  TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x)                                              \
  TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, \
              INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x)                                        \
  TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x)                                              \
  TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, \
              INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x)               \
  ((UNLIKELY((x) != (x))) ? 0                           \
                          : (UNLIKELY(!((x) > (ft)-1))) \
                                ? 0                     \
                                : (UNLIKELY(!((x) < (max)))) ? smax : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F64(x) \
  TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2) \
  static inline t2 name(t1 x) {          \
    t2 result;                           \
    memcpy(&result, &x, sizeof(result)); \
    return result;                       \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)

DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)

DEFINE_REINTERPRET(f64_reinterpret_i64, u64, float64)

DEFINE_REINTERPRET(i64_reinterpret_f64, float64, u64)

static float quiet_nanf(float x) {
    uint32_t tmp;
    memcpy(&tmp, &x, 4);
    tmp |= 0x7fc00000lu;
    memcpy(&x, &tmp, 4);
    return x;
}

static double quiet_nan(double x) {
    uint64_t tmp;
    memcpy(&tmp, &x, 8);
    tmp |= 0x7ff8000000000000llu;
    memcpy(&x, &tmp, 8);
    return x;
}

static double wasm_quiet(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return x;
}

static float wasm_quietf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return x;
}

static double wasm_floor(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return floor(x);
}

static float wasm_floorf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return floorf(x);
}

static double wasm_ceil(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return ceil(x);
}

static float wasm_ceilf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return ceilf(x);
}

static double wasm_trunc(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return trunc(x);
}

static float wasm_truncf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return truncf(x);
}

static float wasm_nearbyintf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return nearbyintf(x);
}

static double wasm_nearbyint(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return nearbyint(x);
}

static float wasm_fabsf(float x) {
    if (UNLIKELY(isnan(x))) {
        uint32_t tmp;
        memcpy(&tmp, &x, 4);
        tmp = tmp & ~(1 << 31);
        memcpy(&x, &tmp, 4);
        return x;
    }
    return fabsf(x);
}

static double wasm_fabs(double x) {
    if (UNLIKELY(isnan(x))) {
        uint64_t tmp;
        memcpy(&tmp, &x, 8);
        tmp = tmp & ~(1ll << 63);
        memcpy(&x, &tmp, 8);
        return x;
    }
    return fabs(x);
}

static double wasm_sqrt(double x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nan(x);
    }
    return sqrt(x);
}

static float wasm_sqrtf(float x) {
    if (UNLIKELY(isnan(x))) {
        return quiet_nanf(x);
    }
    return sqrtf(x);
}

static inline void memory_fill(wasm_rt_memory_t *mem, u32 d, u32 val, u32 n) {
    RANGE_CHECK(mem, d, n);
    memset(mem->data + d, val, n);
}

static inline void memory_copy(wasm_rt_memory_t *dest,
                               const wasm_rt_memory_t *src,
                               u32 dest_addr,
                               u32 src_addr,
                               u32 n) {
    RANGE_CHECK(dest, dest_addr, n);
    RANGE_CHECK(src, src_addr, n);
    memmove(dest->data + dest_addr, src->data + src_addr, n);
}

static inline void memory_init(wasm_rt_memory_t *dest,
                               const u8 *src,
                               u32 src_size,
                               u32 dest_addr,
                               u32 src_addr,
                               u32 n) {
    if (UNLIKELY(src_addr + (uint64_t) n > src_size))
        TRAP(OOB);
    LOAD_DATA((*dest), dest_addr, src + src_addr, n);
}

typedef struct {
    uint32_t func_type_index;
    wasm_rt_function_ptr_t func;
    size_t module_offset;
} wasm_elem_segment_expr_t;

static inline void funcref_table_init(wasm_rt_funcref_table_t *dest,
                                      const wasm_elem_segment_expr_t *src,
                                      u32 src_size,
                                      u32 dest_addr,
                                      u32 src_addr,
                                      u32 n,
                                      void *module_instance,
                                      const u32 *func_types) {
    if (UNLIKELY(src_addr + (uint64_t) n > src_size))
        TRAP(OOB);
    if (UNLIKELY(dest_addr + (uint64_t) n > dest->size))
        TRAP(OOB);
    for (u32 i = 0; i < n; i++) {
        const wasm_elem_segment_expr_t *src_expr = &src[src_addr + i];
        dest->data[dest_addr + i] = (wasm_rt_funcref_t) {
                func_types[src_expr->func_type_index], src_expr->func,
                (char *) module_instance + src_expr->module_offset};
    }
}

// Currently we only support initializing externref tables with ref.null.
static inline void externref_table_init(wasm_rt_externref_table_t *dest,
                                        const wasm_rt_externref_t *src,
                                        u32 src_size,
                                        u32 dest_addr,
                                        u32 src_addr,
                                        u32 n) {
    if (UNLIKELY(src_addr + (uint64_t) n > src_size))
        TRAP(OOB);
    if (UNLIKELY(dest_addr + (uint64_t) n > dest->size))
        TRAP(OOB);
    for (u32 i = 0; i < n; i++) {
        const wasm_rt_externref_t *src_expr = &src[src_addr + i];
        dest->data[dest_addr + i] = *src_expr;
    }
}

#define DEFINE_TABLE_COPY(type)                                              \
  static inline void type##_table_copy(wasm_rt_##type##_table_t* dest,       \
                                       const wasm_rt_##type##_table_t* src,  \
                                       u32 dest_addr, u32 src_addr, u32 n) { \
    if (UNLIKELY(dest_addr + (uint64_t)n > dest->size))                      \
      TRAP(OOB);                                                             \
    if (UNLIKELY(src_addr + (uint64_t)n > src->size))                        \
      TRAP(OOB);                                                             \
                                                                             \
    memmove(dest->data + dest_addr, src->data + src_addr,                    \
            n * sizeof(wasm_rt_##type##_t));                                 \
  }

DEFINE_TABLE_COPY(funcref)

DEFINE_TABLE_COPY(externref)

#define DEFINE_TABLE_GET(type)                        \
  static inline wasm_rt_##type##_t type##_table_get(  \
      const wasm_rt_##type##_table_t* table, u32 i) { \
    if (UNLIKELY(i >= table->size))                   \
      TRAP(OOB);                                      \
    return table->data[i];                            \
  }

DEFINE_TABLE_GET(funcref)

DEFINE_TABLE_GET(externref)

#define DEFINE_TABLE_SET(type)                                               \
  static inline void type##_table_set(const wasm_rt_##type##_table_t* table, \
                                      u32 i, const wasm_rt_##type##_t val) { \
    if (UNLIKELY(i >= table->size))                                          \
      TRAP(OOB);                                                             \
    table->data[i] = val;                                                    \
  }

DEFINE_TABLE_SET(funcref)

DEFINE_TABLE_SET(externref)

#define DEFINE_TABLE_FILL(type)                                               \
  static inline void type##_table_fill(const wasm_rt_##type##_table_t* table, \
                                       u32 d, const wasm_rt_##type##_t val,   \
                                       u32 n) {                               \
    if (UNLIKELY((uint64_t)d + n > table->size))                              \
      TRAP(OOB);                                                              \
    for (uint32_t i = d; i < d + n; i++) {                                    \
      table->data[i] = val;                                                   \
    }                                                                         \
  }

DEFINE_TABLE_FILL(funcref)

DEFINE_TABLE_FILL(externref)

static bool s_module_initialized = false;

static u32 func_types[2];

static void init_func_types(void) {
    func_types[0] = wasm_rt_register_func_type(2, 1, WASM_RT_F64, WASM_RT_F64, WASM_RT_F64);
    func_types[1] = wasm_rt_register_func_type(2, 1, WASM_RT_F64, WASM_RT_I32, WASM_RT_F64);
}

static float64 w2c_pow(Z__instance_t *, float64, float64);

static float64 w2c_pow_helper1(Z__instance_t *, float64, u32);

static const u8 data_segment_data_w2c_d0[] = {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0xf8, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x06, 0xd0, 0xcf, 0x43, 0xeb, 0xfd, 0x4c, 0x3e, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x03, 0xb8, 0xe2, 0x3f,

};

static void init_memories(Z__instance_t *instance) {
    wasm_rt_allocate_memory(&instance->w2c_M0, 0, 10);
    LOAD_DATA(instance->w2c_M0, 1024u, data_segment_data_w2c_d0, 48);
}

static void init_data_instances(Z__instance_t *instance) {
}

static void init_tables(Z__instance_t *instance) {
    wasm_rt_allocate_funcref_table(&instance->w2c_T0, 1, 1);
}

static float64 w2c_pow(Z__instance_t *instance, float64 w2c_p0, float64 w2c_p1) {
    u32 w2c_l2 = 0, w2c_l3 = 0, w2c_l4 = 0, w2c_l5 = 0, w2c_l6 = 0, w2c_l7 = 0, w2c_l8 = 0, w2c_l9 = 0,
            w2c_l10 = 0;
    u64 w2c_l11 = 0, w2c_l12 = 0;
    float64 w2c_l13 = 0, w2c_l14 = 0, w2c_l15 = 0, w2c_l16 = 0, w2c_l17 = 0;
    FUNC_PROLOGUE;
    u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3, w2c_i4, w2c_i5;
    u64 w2c_j0, w2c_j1, w2c_j2, w2c_j3, w2c_j4, w2c_j5;
    float64 w2c_d0_0, w2c_d1, w2c_d2, w2c_d3, w2c_d4, w2c_d5, w2c_d6, w2c_d7,
            w2c_d8, w2c_d9, w2c_d10;
    w2c_d0_0 = 1;
    w2c_l13 = w2c_d0_0;
    w2c_d0_0 = w2c_p1;
    w2c_j0 = i64_reinterpret_f64(w2c_d0_0);
    w2c_l11 = w2c_j0;
    w2c_j1 = 32ull;
    w2c_j0 >>= (w2c_j1 & 63);
    w2c_i0 = (u32) (w2c_j0);
    w2c_l2 = w2c_i0;
    w2c_i1 = 2147483647u;
    w2c_i0 &= w2c_i1;
    w2c_l3 = w2c_i0;
    w2c_j1 = w2c_l11;
    w2c_i1 = (u32) (w2c_j1);
    w2c_l4 = w2c_i1;
    w2c_i0 |= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B0; }
    w2c_d0_0 = w2c_p0;
    w2c_j0 = i64_reinterpret_f64(w2c_d0_0);
    w2c_l12 = w2c_j0;
    w2c_i0 = (u32) (w2c_j0);
    w2c_l5 = w2c_i0;
    w2c_j0 = w2c_l12;
    w2c_j1 = 32ull;
    w2c_j0 >>= (w2c_j1 & 63);
    w2c_i0 = (u32) (w2c_j0);
    w2c_l6 = w2c_i0;
    w2c_i1 = 1072693248u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B1; }
    w2c_i0 = w2c_l5;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B0; }
    w2c_B1:;
    w2c_i0 = w2c_l6;
    w2c_i1 = 2147483647u;
    w2c_i0 &= w2c_i1;
    w2c_l7 = w2c_i0;
    w2c_i1 = 2146435072u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) { goto w2c_B3; }
    w2c_i0 = w2c_l7;
    w2c_i1 = 2146435072u;
    w2c_i0 = w2c_i0 == w2c_i1;
    w2c_i1 = w2c_l5;
    w2c_i2 = 0u;
    w2c_i1 = w2c_i1 != w2c_i2;
    w2c_i0 &= w2c_i1;
    if (w2c_i0) { goto w2c_B3; }
    w2c_i0 = w2c_l3;
    w2c_i1 = 2146435072u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) { goto w2c_B3; }
    w2c_i0 = w2c_l3;
    w2c_i1 = 2146435072u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B2; }
    w2c_i0 = w2c_l4;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B2; }
    w2c_B3:;
    w2c_d0_0 = w2c_p0;
    w2c_d1 = w2c_p1;
    w2c_d0_0 += w2c_d1;
    goto w2c_Bfunc;
    w2c_B2:;
    w2c_j0 = w2c_l12;
    w2c_j1 = 18446744073709551615ull;
    w2c_i0 = (u64) ((s64) w2c_j0 > (s64) w2c_j1);
    if (w2c_i0) { goto w2c_B7; }
    w2c_i0 = 2u;
    w2c_l8 = w2c_i0;
    w2c_i0 = w2c_l3;
    w2c_i1 = 1128267775u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) { goto w2c_B6; }
    w2c_i0 = w2c_l3;
    w2c_i1 = 1072693248u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B7; }
    w2c_i0 = w2c_l3;
    w2c_i1 = 20u;
    w2c_i0 >>= (w2c_i1 & 31);
    w2c_l9 = w2c_i0;
    w2c_i0 = w2c_l3;
    w2c_i1 = 1094713344u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B8; }
    w2c_i0 = 0u;
    w2c_l8 = w2c_i0;
    w2c_i0 = w2c_l4;
    w2c_i1 = 1075u;
    w2c_i2 = w2c_l9;
    w2c_i1 -= w2c_i2;
    w2c_l9 = w2c_i1;
    w2c_i0 >>= (w2c_i1 & 31);
    w2c_l10 = w2c_i0;
    w2c_i1 = w2c_l9;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_i1 = w2c_l4;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B6; }
    w2c_i0 = 2u;
    w2c_i1 = w2c_l10;
    w2c_i2 = 1u;
    w2c_i1 &= w2c_i2;
    w2c_i0 -= w2c_i1;
    w2c_l8 = w2c_i0;
    goto w2c_B6;
    w2c_B8:;
    w2c_i0 = 0u;
    w2c_l8 = w2c_i0;
    w2c_i0 = w2c_l4;
    if (w2c_i0) { goto w2c_B4; }
    w2c_i0 = 0u;
    w2c_l8 = w2c_i0;
    w2c_i0 = w2c_l3;
    w2c_i1 = 1043u;
    w2c_i2 = w2c_l9;
    w2c_i1 -= w2c_i2;
    w2c_l4 = w2c_i1;
    w2c_i0 >>= (w2c_i1 & 31);
    w2c_l9 = w2c_i0;
    w2c_i1 = w2c_l4;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_i1 = w2c_l3;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B5; }
    w2c_i0 = 2u;
    w2c_i1 = w2c_l9;
    w2c_i2 = 1u;
    w2c_i1 &= w2c_i2;
    w2c_i0 -= w2c_i1;
    w2c_l8 = w2c_i0;
    goto w2c_B5;
    w2c_B7:;
    w2c_i0 = 0u;
    w2c_l8 = w2c_i0;
    w2c_B6:;
    w2c_i0 = w2c_l4;
    if (w2c_i0) { goto w2c_B4; }
    w2c_B5:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 2146435072u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B9; }
    w2c_i0 = w2c_l7;
    w2c_i1 = 3222274048u;
    w2c_i0 += w2c_i1;
    w2c_i1 = w2c_l5;
    w2c_i0 |= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B0; }
    w2c_i0 = w2c_l7;
    w2c_i1 = 1072693248u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B10; }
    w2c_d0_0 = w2c_p1;
    w2c_d1 = 0;
    w2c_j2 = w2c_l11;
    w2c_j3 = 18446744073709551615ull;
    w2c_i2 = (u64) ((s64) w2c_j2 > (s64) w2c_j3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B10:;
    w2c_d0_0 = 0;
    w2c_d1 = w2c_p1;
    w2c_d1 = -(w2c_d1);
    w2c_j2 = w2c_l11;
    w2c_j3 = 18446744073709551615ull;
    w2c_i2 = (u64) ((s64) w2c_j2 > (s64) w2c_j3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B9:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 1072693248u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B11; }
    w2c_j0 = w2c_l11;
    w2c_j1 = 18446744073709551615ull;
    w2c_i0 = (u64) ((s64) w2c_j0 <= (s64) w2c_j1);
    if (w2c_i0) { goto w2c_B12; }
    w2c_d0_0 = w2c_p0;
    goto w2c_Bfunc;
    w2c_B12:;
    w2c_d0_0 = 1;
    w2c_d1 = w2c_p0;
    w2c_d0_0 /= w2c_d1;
    goto w2c_Bfunc;
    w2c_B11:;
    w2c_i0 = w2c_l2;
    w2c_i1 = 1073741824u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B13; }
    w2c_d0_0 = w2c_p0;
    w2c_d1 = w2c_p0;
    w2c_d0_0 *= w2c_d1;
    goto w2c_Bfunc;
    w2c_B13:;
    w2c_i0 = w2c_l2;
    w2c_i1 = 1071644672u;
    w2c_i0 = w2c_i0 != w2c_i1;
    if (w2c_i0) { goto w2c_B4; }
    w2c_j0 = w2c_l12;
    w2c_j1 = 0ull;
    w2c_i0 = (u64) ((s64) w2c_j0 < (s64) w2c_j1);
    if (w2c_i0) { goto w2c_B4; }
    w2c_d0_0 = w2c_p0;
    w2c_d0_0 = wasm_sqrt(w2c_d0_0);
    goto w2c_Bfunc;
    w2c_B4:;
    w2c_d0_0 = w2c_p0;
    w2c_d0_0 = wasm_fabs(w2c_d0_0);
    w2c_l13 = w2c_d0_0;
    w2c_i0 = w2c_l5;
    if (w2c_i0) { goto w2c_B14; }
    w2c_i0 = w2c_l6;
    w2c_i1 = 1073741823u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 1072693248u;
    w2c_i0 = w2c_i0 == w2c_i1;
    if (w2c_i0) { goto w2c_B15; }
    w2c_i0 = w2c_l7;
    if (w2c_i0) { goto w2c_B14; }
    w2c_B15:;
    w2c_d0_0 = 1;
    w2c_d1 = w2c_l13;
    w2c_d0_0 /= w2c_d1;
    w2c_d1 = w2c_l13;
    w2c_j2 = w2c_l11;
    w2c_j3 = 0ull;
    w2c_i2 = (u64) ((s64) w2c_j2 < (s64) w2c_j3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_j0 = w2c_l12;
    w2c_j1 = 18446744073709551615ull;
    w2c_i0 = (u64) ((s64) w2c_j0 > (s64) w2c_j1);
    if (w2c_i0) { goto w2c_B0; }
    w2c_i0 = w2c_l8;
    w2c_i1 = w2c_l7;
    w2c_i2 = 3222274048u;
    w2c_i1 += w2c_i2;
    w2c_i0 |= w2c_i1;
    if (w2c_i0) { goto w2c_B16; }
    w2c_d0_0 = w2c_l13;
    w2c_d1 = w2c_l13;
    w2c_d0_0 -= w2c_d1;
    w2c_p1 = w2c_d0_0;
    w2c_d1 = w2c_p1;
    w2c_d0_0 /= w2c_d1;
    goto w2c_Bfunc;
    w2c_B16:;
    w2c_d0_0 = w2c_l13;
    w2c_d0_0 = -(w2c_d0_0);
    w2c_d1 = w2c_l13;
    w2c_i2 = w2c_l8;
    w2c_i3 = 1u;
    w2c_i2 = w2c_i2 == w2c_i3;
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B14:;
    w2c_d0_0 = 1;
    w2c_l14 = w2c_d0_0;
    w2c_j0 = w2c_l12;
    w2c_j1 = 18446744073709551615ull;
    w2c_i0 = (u64) ((s64) w2c_j0 > (s64) w2c_j1);
    if (w2c_i0) { goto w2c_B17; }
    w2c_i0 = w2c_l8;
    switch (w2c_i0) {
        case 0:
            goto w2c_B19;
        case 1:
            goto w2c_B18;
        default:
            goto w2c_B17;
    }
    w2c_B19:;
    w2c_d0_0 = w2c_p0;
    w2c_d1 = w2c_p0;
    w2c_d0_0 -= w2c_d1;
    w2c_p1 = w2c_d0_0;
    w2c_d1 = w2c_p1;
    w2c_d0_0 /= w2c_d1;
    goto w2c_Bfunc;
    w2c_B18:;
    w2c_d0_0 = -1;
    w2c_l14 = w2c_d0_0;
    w2c_B17:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 1105199105u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B21; }
    w2c_i0 = w2c_l3;
    w2c_i1 = 1139802113u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B22; }
    w2c_i0 = w2c_l7;
    w2c_i1 = 1072693247u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) { goto w2c_B23; }
    w2c_d0_0 = INFINITY;
    w2c_d1 = 0;
    w2c_j2 = w2c_l11;
    w2c_j3 = 0ull;
    w2c_i2 = (u64) ((s64) w2c_j2 < (s64) w2c_j3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B23:;
    w2c_d0_0 = INFINITY;
    w2c_d1 = 0;
    w2c_i2 = w2c_l2;
    w2c_i3 = 0u;
    w2c_i2 = (u32) ((s32) w2c_i2 > (s32) w2c_i3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B22:;
    w2c_i0 = w2c_l7;
    w2c_i1 = 1072693246u;
    w2c_i0 = w2c_i0 > w2c_i1;
    if (w2c_i0) { goto w2c_B24; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = w2c_l14;
    w2c_d2 = 1e-300;
    w2c_d1 *= w2c_d2;
    w2c_d2 = 1e-300;
    w2c_d1 *= w2c_d2;
    w2c_j2 = w2c_l11;
    w2c_j3 = 0ull;
    w2c_i2 = (u64) ((s64) w2c_j2 < (s64) w2c_j3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B24:;
    w2c_i0 = w2c_l7;
    w2c_i1 = 1072693249u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B25; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = w2c_l14;
    w2c_d2 = 1e-300;
    w2c_d1 *= w2c_d2;
    w2c_d2 = 1e-300;
    w2c_d1 *= w2c_d2;
    w2c_i2 = w2c_l2;
    w2c_i3 = 0u;
    w2c_i2 = (u32) ((s32) w2c_i2 > (s32) w2c_i3);
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    goto w2c_Bfunc;
    w2c_B25:;
    w2c_d0_0 = w2c_l13;
    w2c_d1 = -1;
    w2c_d0_0 += w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_d1 = 1.9259629911266175e-08;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = w2c_p0;
    w2c_d2 = w2c_p0;
    w2c_d1 *= w2c_d2;
    w2c_d2 = 0.5;
    w2c_d3 = w2c_p0;
    w2c_d4 = w2c_p0;
    w2c_d5 = -0.25;
    w2c_d4 *= w2c_d5;
    w2c_d5 = 0.33333333333333331;
    w2c_d4 += w2c_d5;
    w2c_d3 *= w2c_d4;
    w2c_d2 -= w2c_d3;
    w2c_d1 *= w2c_d2;
    w2c_d2 = -1.4426950408889634;
    w2c_d1 *= w2c_d2;
    w2c_d0_0 += w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_d1 = w2c_l13;
    w2c_d2 = w2c_p0;
    w2c_d3 = 1.4426950216293335;
    w2c_d2 *= w2c_d3;
    w2c_l15 = w2c_d2;
    w2c_d1 += w2c_d2;
    w2c_j1 = i64_reinterpret_f64(w2c_d1);
    w2c_j2 = 18446744069414584320ull;
    w2c_j1 &= w2c_j2;
    w2c_d1 = f64_reinterpret_i64(w2c_j1);
    w2c_p0 = w2c_d1;
    w2c_d2 = w2c_l15;
    w2c_d1 -= w2c_d2;
    w2c_d0_0 -= w2c_d1;
    w2c_l15 = w2c_d0_0;
    goto w2c_B20;
    w2c_B21:;
    w2c_d0_0 = w2c_l13;
    w2c_d1 = 9007199254740992;
    w2c_d0_0 *= w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_d1 = w2c_l13;
    w2c_i2 = w2c_l7;
    w2c_i3 = 1048576u;
    w2c_i2 = w2c_i2 < w2c_i3;
    w2c_l3 = w2c_i2;
    w2c_d0_0 = w2c_i2 ? w2c_d0_0 : w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_d0_0 = w2c_p0;
    w2c_j0 = i64_reinterpret_f64(w2c_d0_0);
    w2c_j1 = 32ull;
    w2c_j0 >>= (w2c_j1 & 63);
    w2c_i0 = (u32) (w2c_j0);
    w2c_i1 = w2c_l7;
    w2c_i2 = w2c_l3;
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_i1 = 1048575u;
    w2c_i0 &= w2c_i1;
    w2c_l4 = w2c_i0;
    w2c_i1 = 1072693248u;
    w2c_i0 |= w2c_i1;
    w2c_l5 = w2c_i0;
    w2c_i0 = 4294966220u;
    w2c_i1 = 4294966273u;
    w2c_i2 = w2c_l3;
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_i1 = w2c_l2;
    w2c_i2 = 20u;
    w2c_i1 = (u32) ((s32) w2c_i1 >> (w2c_i2 & 31));
    w2c_i0 += w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_i0 = 0u;
    w2c_l3 = w2c_i0;
    w2c_i0 = w2c_l4;
    w2c_i1 = 235663u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B26; }
    w2c_i0 = w2c_l4;
    w2c_i1 = 767610u;
    w2c_i0 = w2c_i0 >= w2c_i1;
    if (w2c_i0) { goto w2c_B27; }
    w2c_i0 = 1u;
    w2c_l3 = w2c_i0;
    goto w2c_B26;
    w2c_B27:;
    w2c_i0 = w2c_l4;
    w2c_i1 = 1071644672u;
    w2c_i0 |= w2c_i1;
    w2c_l5 = w2c_i0;
    w2c_i0 = w2c_l2;
    w2c_i1 = 1u;
    w2c_i0 += w2c_i1;
    w2c_l2 = w2c_i0;
    w2c_B26:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 3u;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_l4 = w2c_i0;
    w2c_i1 = 1040u;
    w2c_i0 += w2c_i1;
    w2c_d0_0 = f64_load(&instance->w2c_M0, (u64) (w2c_i0));
    w2c_d1 = 1;
    w2c_i2 = w2c_l4;
    w2c_i3 = 1024u;
    w2c_i2 += w2c_i3;
    w2c_d2 = f64_load(&instance->w2c_M0, (u64) (w2c_i2));
    w2c_p0 = w2c_d2;
    w2c_i3 = w2c_l5;
    w2c_j3 = (u64) (w2c_i3);
    w2c_j4 = 32ull;
    w2c_j3 <<= (w2c_j4 & 63);
    w2c_d4 = w2c_l13;
    w2c_j4 = i64_reinterpret_f64(w2c_d4);
    w2c_j5 = 4294967295ull;
    w2c_j4 &= w2c_j5;
    w2c_j3 |= w2c_j4;
    w2c_d3 = f64_reinterpret_i64(w2c_j3);
    w2c_l16 = w2c_d3;
    w2c_d2 += w2c_d3;
    w2c_d1 /= w2c_d2;
    w2c_l13 = w2c_d1;
    w2c_d2 = w2c_l16;
    w2c_d3 = w2c_p0;
    w2c_d2 -= w2c_d3;
    w2c_l15 = w2c_d2;
    w2c_i3 = w2c_l3;
    w2c_i4 = 18u;
    w2c_i3 <<= (w2c_i4 & 31);
    w2c_i4 = w2c_l5;
    w2c_i5 = 1u;
    w2c_i4 >>= (w2c_i5 & 31);
    w2c_i3 += w2c_i4;
    w2c_i4 = 537395200u;
    w2c_i3 += w2c_i4;
    w2c_j3 = (u64) (w2c_i3);
    w2c_j4 = 32ull;
    w2c_j3 <<= (w2c_j4 & 63);
    w2c_d3 = f64_reinterpret_i64(w2c_j3);
    w2c_l17 = w2c_d3;
    w2c_d4 = w2c_l15;
    w2c_d5 = w2c_l13;
    w2c_d4 *= w2c_d5;
    w2c_l15 = w2c_d4;
    w2c_j4 = i64_reinterpret_f64(w2c_d4);
    w2c_j5 = 18446744069414584320ull;
    w2c_j4 &= w2c_j5;
    w2c_d4 = f64_reinterpret_i64(w2c_j4);
    w2c_l13 = w2c_d4;
    w2c_d3 *= w2c_d4;
    w2c_d2 -= w2c_d3;
    w2c_d3 = w2c_l16;
    w2c_d4 = w2c_l17;
    w2c_d5 = w2c_p0;
    w2c_d4 -= w2c_d5;
    w2c_d3 -= w2c_d4;
    w2c_d4 = w2c_l13;
    w2c_d3 *= w2c_d4;
    w2c_d2 -= w2c_d3;
    w2c_d1 *= w2c_d2;
    w2c_p0 = w2c_d1;
    w2c_d2 = w2c_l13;
    w2c_d3 = w2c_l13;
    w2c_d2 *= w2c_d3;
    w2c_l16 = w2c_d2;
    w2c_d3 = 3;
    w2c_d2 += w2c_d3;
    w2c_d3 = w2c_p0;
    w2c_d4 = w2c_l15;
    w2c_d5 = w2c_l13;
    w2c_d4 += w2c_d5;
    w2c_d3 *= w2c_d4;
    w2c_d4 = w2c_l15;
    w2c_d5 = w2c_l15;
    w2c_d4 *= w2c_d5;
    w2c_p0 = w2c_d4;
    w2c_d5 = w2c_p0;
    w2c_d4 *= w2c_d5;
    w2c_d5 = w2c_p0;
    w2c_d6 = w2c_p0;
    w2c_d7 = w2c_p0;
    w2c_d8 = w2c_p0;
    w2c_d9 = w2c_p0;
    w2c_d10 = 0.20697501780033842;
    w2c_d9 *= w2c_d10;
    w2c_d10 = 0.23066074577556175;
    w2c_d9 += w2c_d10;
    w2c_d8 *= w2c_d9;
    w2c_d9 = 0.27272812380853401;
    w2c_d8 += w2c_d9;
    w2c_d7 *= w2c_d8;
    w2c_d8 = 0.33333332981837743;
    w2c_d7 += w2c_d8;
    w2c_d6 *= w2c_d7;
    w2c_d7 = 0.42857142857855018;
    w2c_d6 += w2c_d7;
    w2c_d5 *= w2c_d6;
    w2c_d6 = 0.59999999999999465;
    w2c_d5 += w2c_d6;
    w2c_d4 *= w2c_d5;
    w2c_d3 += w2c_d4;
    w2c_l17 = w2c_d3;
    w2c_d2 += w2c_d3;
    w2c_j2 = i64_reinterpret_f64(w2c_d2);
    w2c_j3 = 18446744069414584320ull;
    w2c_j2 &= w2c_j3;
    w2c_d2 = f64_reinterpret_i64(w2c_j2);
    w2c_p0 = w2c_d2;
    w2c_d1 *= w2c_d2;
    w2c_d2 = w2c_l15;
    w2c_d3 = w2c_l17;
    w2c_d4 = w2c_p0;
    w2c_d5 = -3;
    w2c_d4 += w2c_d5;
    w2c_d5 = w2c_l16;
    w2c_d4 -= w2c_d5;
    w2c_d3 -= w2c_d4;
    w2c_d2 *= w2c_d3;
    w2c_d1 += w2c_d2;
    w2c_l15 = w2c_d1;
    w2c_d2 = w2c_l15;
    w2c_d3 = w2c_l13;
    w2c_d4 = w2c_p0;
    w2c_d3 *= w2c_d4;
    w2c_l13 = w2c_d3;
    w2c_d2 += w2c_d3;
    w2c_j2 = i64_reinterpret_f64(w2c_d2);
    w2c_j3 = 18446744069414584320ull;
    w2c_j2 &= w2c_j3;
    w2c_d2 = f64_reinterpret_i64(w2c_j2);
    w2c_p0 = w2c_d2;
    w2c_d3 = w2c_l13;
    w2c_d2 -= w2c_d3;
    w2c_d1 -= w2c_d2;
    w2c_d2 = 0.96179669392597555;
    w2c_d1 *= w2c_d2;
    w2c_d2 = w2c_p0;
    w2c_d3 = -7.0284616509527583e-09;
    w2c_d2 *= w2c_d3;
    w2c_d1 += w2c_d2;
    w2c_d0_0 += w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_i1 = w2c_l4;
    w2c_i2 = 1056u;
    w2c_i1 += w2c_i2;
    w2c_d1 = f64_load(&instance->w2c_M0, (u64) (w2c_i1));
    w2c_l15 = w2c_d1;
    w2c_d2 = w2c_l13;
    w2c_d3 = w2c_p0;
    w2c_d4 = 0.96179670095443726;
    w2c_d3 *= w2c_d4;
    w2c_l16 = w2c_d3;
    w2c_d2 += w2c_d3;
    w2c_d1 += w2c_d2;
    w2c_i2 = w2c_l2;
    w2c_d2 = (float64) (s32) (w2c_i2);
    w2c_l13 = w2c_d2;
    w2c_d1 += w2c_d2;
    w2c_j1 = i64_reinterpret_f64(w2c_d1);
    w2c_j2 = 18446744069414584320ull;
    w2c_j1 &= w2c_j2;
    w2c_d1 = f64_reinterpret_i64(w2c_j1);
    w2c_p0 = w2c_d1;
    w2c_d2 = w2c_l13;
    w2c_d1 -= w2c_d2;
    w2c_d2 = w2c_l15;
    w2c_d1 -= w2c_d2;
    w2c_d2 = w2c_l16;
    w2c_d1 -= w2c_d2;
    w2c_d0_0 -= w2c_d1;
    w2c_l15 = w2c_d0_0;
    w2c_B20:;
    w2c_d0_0 = w2c_p0;
    w2c_j1 = w2c_l11;
    w2c_j2 = 18446744069414584320ull;
    w2c_j1 &= w2c_j2;
    w2c_d1 = f64_reinterpret_i64(w2c_j1);
    w2c_l16 = w2c_d1;
    w2c_d0_0 *= w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_d1 = w2c_l15;
    w2c_d2 = w2c_p1;
    w2c_d1 *= w2c_d2;
    w2c_d2 = w2c_p1;
    w2c_d3 = w2c_l16;
    w2c_d2 -= w2c_d3;
    w2c_d3 = w2c_p0;
    w2c_d2 *= w2c_d3;
    w2c_d1 += w2c_d2;
    w2c_p1 = w2c_d1;
    w2c_d0_0 += w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_j0 = i64_reinterpret_f64(w2c_d0_0);
    w2c_l11 = w2c_j0;
    w2c_i0 = (u32) (w2c_j0);
    w2c_l3 = w2c_i0;
    w2c_j0 = w2c_l11;
    w2c_j1 = 32ull;
    w2c_j0 >>= (w2c_j1 & 63);
    w2c_i0 = (u32) (w2c_j0);
    w2c_l5 = w2c_i0;
    w2c_i1 = 1083179008u;
    w2c_i0 = (u32) ((s32) w2c_i0 < (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B29; }
    w2c_i0 = w2c_l5;
    w2c_i1 = 3211788288u;
    w2c_i0 += w2c_i1;
    w2c_i1 = w2c_l3;
    w2c_i0 |= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B30; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    goto w2c_Bfunc;
    w2c_B30:;
    w2c_d0_0 = w2c_p1;
    w2c_d1 = 8.0085662595372941e-17;
    w2c_d0_0 += w2c_d1;
    w2c_d1 = w2c_p0;
    w2c_d2 = w2c_l13;
    w2c_d1 -= w2c_d2;
    w2c_i0 = w2c_d0_0 > w2c_d1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B28; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1.0000000000000001e+300;
    w2c_d0_0 *= w2c_d1;
    goto w2c_Bfunc;
    w2c_B29:;
    w2c_i0 = w2c_l5;
    w2c_i1 = 2147482624u;
    w2c_i0 &= w2c_i1;
    w2c_i1 = 1083231232u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B28; }
    w2c_i0 = w2c_l5;
    w2c_i1 = 1064252416u;
    w2c_i0 += w2c_i1;
    w2c_i1 = w2c_l3;
    w2c_i0 |= w2c_i1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B31; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1e-300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1e-300;
    w2c_d0_0 *= w2c_d1;
    goto w2c_Bfunc;
    w2c_B31:;
    w2c_d0_0 = w2c_p1;
    w2c_d1 = w2c_p0;
    w2c_d2 = w2c_l13;
    w2c_d1 -= w2c_d2;
    w2c_i0 = w2c_d0_0 <= w2c_d1;
    w2c_i0 = !(w2c_i0);
    if (w2c_i0) { goto w2c_B28; }
    w2c_d0_0 = w2c_l14;
    w2c_d1 = 1e-300;
    w2c_d0_0 *= w2c_d1;
    w2c_d1 = 1e-300;
    w2c_d0_0 *= w2c_d1;
    goto w2c_Bfunc;
    w2c_B28:;
    w2c_i0 = 0u;
    w2c_l3 = w2c_i0;
    w2c_i0 = w2c_l5;
    w2c_i1 = 2147483647u;
    w2c_i0 &= w2c_i1;
    w2c_l4 = w2c_i0;
    w2c_i1 = 1071644673u;
    w2c_i0 = w2c_i0 < w2c_i1;
    if (w2c_i0) { goto w2c_B32; }
    w2c_i0 = 0u;
    w2c_i1 = 1048576u;
    w2c_i2 = w2c_l4;
    w2c_i3 = 20u;
    w2c_i2 >>= (w2c_i3 & 31);
    w2c_i3 = 4294966274u;
    w2c_i2 += w2c_i3;
    w2c_i1 >>= (w2c_i2 & 31);
    w2c_i2 = w2c_l5;
    w2c_i1 += w2c_i2;
    w2c_l5 = w2c_i1;
    w2c_i2 = 1048575u;
    w2c_i1 &= w2c_i2;
    w2c_i2 = 1048576u;
    w2c_i1 |= w2c_i2;
    w2c_i2 = 1043u;
    w2c_i3 = w2c_l5;
    w2c_i4 = 20u;
    w2c_i3 >>= (w2c_i4 & 31);
    w2c_i4 = 2047u;
    w2c_i3 &= w2c_i4;
    w2c_l4 = w2c_i3;
    w2c_i2 -= w2c_i3;
    w2c_i1 >>= (w2c_i2 & 31);
    w2c_l3 = w2c_i1;
    w2c_i0 -= w2c_i1;
    w2c_i1 = w2c_l3;
    w2c_j2 = w2c_l11;
    w2c_j3 = 0ull;
    w2c_i2 = (u64) ((s64) w2c_j2 < (s64) w2c_j3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_l3 = w2c_i0;
    w2c_d0_0 = w2c_p1;
    w2c_d1 = w2c_l13;
    w2c_i2 = 4293918720u;
    w2c_i3 = w2c_l4;
    w2c_i4 = 4294966273u;
    w2c_i3 += w2c_i4;
    w2c_i2 = (u32) ((s32) w2c_i2 >> (w2c_i3 & 31));
    w2c_i3 = w2c_l5;
    w2c_i2 &= w2c_i3;
    w2c_j2 = (u64) (w2c_i2);
    w2c_j3 = 32ull;
    w2c_j2 <<= (w2c_j3 & 63);
    w2c_d2 = f64_reinterpret_i64(w2c_j2);
    w2c_d1 -= w2c_d2;
    w2c_l13 = w2c_d1;
    w2c_d0_0 += w2c_d1;
    w2c_j0 = i64_reinterpret_f64(w2c_d0_0);
    w2c_l11 = w2c_j0;
    w2c_B32:;
    w2c_i0 = w2c_l3;
    w2c_i1 = 20u;
    w2c_i0 <<= (w2c_i1 & 31);
    w2c_j1 = w2c_l11;
    w2c_j2 = 18446744069414584320ull;
    w2c_j1 &= w2c_j2;
    w2c_d1 = f64_reinterpret_i64(w2c_j1);
    w2c_p0 = w2c_d1;
    w2c_d2 = 0.69314718246459961;
    w2c_d1 *= w2c_d2;
    w2c_l15 = w2c_d1;
    w2c_d2 = w2c_p1;
    w2c_d3 = w2c_p0;
    w2c_d4 = w2c_l13;
    w2c_d3 -= w2c_d4;
    w2c_d2 -= w2c_d3;
    w2c_d3 = 0.69314718055994529;
    w2c_d2 *= w2c_d3;
    w2c_d3 = w2c_p0;
    w2c_d4 = -1.904654299957768e-09;
    w2c_d3 *= w2c_d4;
    w2c_d2 += w2c_d3;
    w2c_l13 = w2c_d2;
    w2c_d1 += w2c_d2;
    w2c_p1 = w2c_d1;
    w2c_d2 = w2c_p1;
    w2c_d3 = w2c_p1;
    w2c_d4 = w2c_p1;
    w2c_d5 = w2c_p1;
    w2c_d4 *= w2c_d5;
    w2c_p0 = w2c_d4;
    w2c_d5 = w2c_p0;
    w2c_d6 = w2c_p0;
    w2c_d7 = w2c_p0;
    w2c_d8 = w2c_p0;
    w2c_d9 = 4.1381367970572385e-08;
    w2c_d8 *= w2c_d9;
    w2c_d9 = -1.6533902205465252e-06;
    w2c_d8 += w2c_d9;
    w2c_d7 *= w2c_d8;
    w2c_d8 = 6.6137563214379344e-05;
    w2c_d7 += w2c_d8;
    w2c_d6 *= w2c_d7;
    w2c_d7 = -0.0027777777777015593;
    w2c_d6 += w2c_d7;
    w2c_d5 *= w2c_d6;
    w2c_d6 = 0.16666666666666602;
    w2c_d5 += w2c_d6;
    w2c_d4 *= w2c_d5;
    w2c_d3 -= w2c_d4;
    w2c_p0 = w2c_d3;
    w2c_d2 *= w2c_d3;
    w2c_d3 = w2c_p0;
    w2c_d4 = -2;
    w2c_d3 += w2c_d4;
    w2c_d2 /= w2c_d3;
    w2c_d3 = w2c_l13;
    w2c_d4 = w2c_p1;
    w2c_d5 = w2c_l15;
    w2c_d4 -= w2c_d5;
    w2c_d3 -= w2c_d4;
    w2c_p0 = w2c_d3;
    w2c_d4 = w2c_p1;
    w2c_d5 = w2c_p0;
    w2c_d4 *= w2c_d5;
    w2c_d3 += w2c_d4;
    w2c_d2 -= w2c_d3;
    w2c_d1 -= w2c_d2;
    w2c_d2 = 1;
    w2c_d1 += w2c_d2;
    w2c_p1 = w2c_d1;
    w2c_j1 = i64_reinterpret_f64(w2c_d1);
    w2c_l11 = w2c_j1;
    w2c_j2 = 32ull;
    w2c_j1 >>= (w2c_j2 & 63);
    w2c_i1 = (u32) (w2c_j1);
    w2c_i0 += w2c_i1;
    w2c_l5 = w2c_i0;
    w2c_i1 = 1048575u;
    w2c_i0 = (u32) ((s32) w2c_i0 > (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B34; }
    w2c_d0_0 = w2c_p1;
    w2c_i1 = w2c_l3;
    w2c_d0_0 = w2c_pow_helper1(instance, w2c_d0_0, w2c_i1);
    w2c_p1 = w2c_d0_0;
    goto w2c_B33;
    w2c_B34:;
    w2c_i0 = w2c_l5;
    w2c_j0 = (u64) (w2c_i0);
    w2c_j1 = 32ull;
    w2c_j0 <<= (w2c_j1 & 63);
    w2c_j1 = w2c_l11;
    w2c_j2 = 4294967295ull;
    w2c_j1 &= w2c_j2;
    w2c_j0 |= w2c_j1;
    w2c_d0_0 = f64_reinterpret_i64(w2c_j0);
    w2c_p1 = w2c_d0_0;
    w2c_B33:;
    w2c_d0_0 = w2c_l14;
    w2c_d1 = w2c_p1;
    w2c_d0_0 *= w2c_d1;
    w2c_l13 = w2c_d0_0;
    w2c_B0:;
    w2c_d0_0 = w2c_l13;
    w2c_Bfunc:;
    FUNC_EPILOGUE;
    return w2c_d0_0;
}

static float64 w2c_pow_helper1(Z__instance_t *instance, float64 w2c_p0, u32 w2c_p1) {
    FUNC_PROLOGUE;
    u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3;
    u64 w2c_j1, w2c_j2;
    float64 w2c_d0_0, w2c_d1;
    w2c_i0 = w2c_p1;
    w2c_i1 = 1024u;
    w2c_i0 = (u32) ((s32) w2c_i0 < (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B1; }
    w2c_d0_0 = w2c_p0;
    w2c_d1 = 8.9884656743115795e+307;
    w2c_d0_0 *= w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_i0 = w2c_p1;
    w2c_i1 = 2047u;
    w2c_i0 = (u32) ((s32) w2c_i0 >= (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B2; }
    w2c_i0 = w2c_p1;
    w2c_i1 = 4294966273u;
    w2c_i0 += w2c_i1;
    w2c_p1 = w2c_i0;
    goto w2c_B0;
    w2c_B2:;
    w2c_d0_0 = w2c_p0;
    w2c_d1 = 8.9884656743115795e+307;
    w2c_d0_0 *= w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_i0 = w2c_p1;
    w2c_i1 = 3069u;
    w2c_i2 = w2c_p1;
    w2c_i3 = 3069u;
    w2c_i2 = (u32) ((s32) w2c_i2 < (s32) w2c_i3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_i1 = 4294965250u;
    w2c_i0 += w2c_i1;
    w2c_p1 = w2c_i0;
    goto w2c_B0;
    w2c_B1:;
    w2c_i0 = w2c_p1;
    w2c_i1 = 4294966273u;
    w2c_i0 = (u32) ((s32) w2c_i0 > (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B0; }
    w2c_d0_0 = w2c_p0;
    w2c_d1 = 2.2250738585072014e-308;
    w2c_d0_0 *= w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_i0 = w2c_p1;
    w2c_i1 = 4294965251u;
    w2c_i0 = (u32) ((s32) w2c_i0 <= (s32) w2c_i1);
    if (w2c_i0) { goto w2c_B3; }
    w2c_i0 = w2c_p1;
    w2c_i1 = 1022u;
    w2c_i0 += w2c_i1;
    w2c_p1 = w2c_i0;
    goto w2c_B0;
    w2c_B3:;
    w2c_d0_0 = w2c_p0;
    w2c_d1 = 2.2250738585072014e-308;
    w2c_d0_0 *= w2c_d1;
    w2c_p0 = w2c_d0_0;
    w2c_i0 = w2c_p1;
    w2c_i1 = 4294964230u;
    w2c_i2 = w2c_p1;
    w2c_i3 = 4294964230u;
    w2c_i2 = (u32) ((s32) w2c_i2 > (s32) w2c_i3);
    w2c_i0 = w2c_i2 ? w2c_i0 : w2c_i1;
    w2c_i1 = 2044u;
    w2c_i0 += w2c_i1;
    w2c_p1 = w2c_i0;
    w2c_B0:;
    w2c_d0_0 = w2c_p0;
    w2c_i1 = w2c_p1;
    w2c_i2 = 1023u;
    w2c_i1 += w2c_i2;
    w2c_j1 = (u64) (w2c_i1);
    w2c_j2 = 52ull;
    w2c_j1 <<= (w2c_j2 & 63);
    w2c_d1 = f64_reinterpret_i64(w2c_j1);
    w2c_d0_0 *= w2c_d1;
    FUNC_EPILOGUE;
    return w2c_d0_0;
}

void Z__init_module(void) {
    assert(wasm_rt_is_initialized());
    s_module_initialized = true;
    init_func_types();
}

void Z__instantiate(Z__instance_t *instance) {
    assert(wasm_rt_is_initialized());
    assert(s_module_initialized);
    init_memories(instance);
    init_tables(instance);
    init_data_instances(instance);
}

void Z__free(Z__instance_t *instance) {
    wasm_rt_free_funcref_table(&instance->w2c_T0);
    wasm_rt_free_memory(&instance->w2c_M0);
}
