name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libcurl4-openssl-dev \
          libreadline-dev
    
    - name: Configure CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DSTRICT=0 .
    
    - name: Build
      run: |
        make -j$(nproc)
      continue-on-error: false
        
    - name: Check if build succeeded
      run: |
        if [ -f wasp ]; then
          echo "Build succeeded - wasp binary exists"
          ls -la wasp
        else
          echo "Build failed - wasp binary not found"
          exit 1
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasp-build
        path: |
          wasp
          wasp-*
          *.wasm
        retention-days: 1